### ISSUE TITLE
Improve folder system

### ISSUE THREAD

**Issue by Siphalor** [DaeZak/crafttweaker-vim-highlighting#1]
It would be nice if the `ftdetect` and `syntax` folder were located in the project root directory.

This would make work with plugin managers such as [vim-pathogen](https://github.com/tpope/vim-pathogen) much easier.

Nevertheless it's a really nice plugin ;-)

**Comment by DaeZak** [comment]
Thanks!  I went and checked out guidelines for developing pathogen plugins and sure enough - I was not inline with how such a thing should be structured.  I've pushed a commit that should fix this.
